<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0;net10.0-windows10.0.22621.0;net10.0-android;net10.0-ios;</TargetFrameworks>
		<LangVersion>14.0</LangVersion>
		<!-- Ensures the .xr.xml files are generated in a proper layout folder -->
		<GenerateLibraryLayout>true</GenerateLibraryLayout>
		<RootNamespace>AsyncWebView</RootNamespace>
		<Authors>nventive</Authors>
		<Company>nventive</Company>
		<AssemblyName>AsyncWebView.Uno.WinUI</AssemblyName>
		<PackageId>AsyncWebView.Uno.WinUI</PackageId>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageTags>async;webview;mvvm;maui;winui;ios;android</PackageTags>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/nventive/AsyncWebView</PackageProjectUrl>
		<DefineConstants>$(DefineConstants);WINUI</DefineConstants>

		<!-- Needed for Source Link support -->
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)'=='net10.0'">
		<DefineConstants>$(DefineConstants);__WASM__</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Uno.WinUI" Version="6.3.62" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
		<PackageReference Include="Uno.Core" Version="4.0.1" />
		<PackageReference Include="Uno.Core.Extensions.Logging" Version="4.0.1" />
	</ItemGroup>

	<ItemGroup>
		<!-- Needed for Source Link support -->
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.102" PrivateAssets="All" />
	</ItemGroup>

	<PropertyGroup Condition="'$(TargetFramework)'=='net10.0-windows10.0.22621.0'">
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<WindowsSdkPackageVersion>10.0.22621.38</WindowsSdkPackageVersion>

		<!-- 
			Needed to use unsafe code for interop with WinRT.

			WinRT.SourceGenerator\Generator.WinRTAotSourceGenerator\WinRTGenericInstantiation.g.cs(450,31,450,48):
				error CS0227: Unsafe code may only appear if compiling with /unsafe
		-->
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<Import Project="winappsdk-workaround.targets" />
	<Import Project="..\Shared\Shared.projitems" Label="Shared" />
</Project>